name = "efficia-v2"
compatibility_date = "2026-07-15"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "efficia_knowledge_base"
database_id = "deabe0a6-d130-418b-8b88-59b9ead17970"
preview_database_id = "579fd946-f939-49d3-a43c-5c4491b2a10c"

[[d1_databases]]
binding = "ORDERS_DB"
database_name = "efficia_orders"
database_id = "216a7d6a-56d2-4a08-b472-c3462f3280f7"
preview_database_id = "09058f6c-cdb7-4a5d-bf96-8d1a67baf607"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "efficia-knowledge-preview"
database_id = "579fd946-f939-49d3-a43c-5c4491b2a10c"

[[env.preview.d1_databases]]
binding = "ORDERS_DB"
database_name = "efficia-orders-preview"
database_id = "09058f6c-cdb7-4a5d-bf96-8d1a67baf607"
