/* ============ GRILLE — critères, 100 points ============ */
const GRILLE = [
{key:"informations", cat:"Informations essentielles", pts:CONFIG.poids.informations.total, criteres:[
 {key:"revendiquee", q:"La fiche est-elle revendiquée et vérifiée ?", aide:"Ouvrir la fiche sur Maps : une fiche non revendiquée affiche « Vous êtes le propriétaire ? ».", max:CONFIG.poids.informations.revendiquee,
  opts:[["Oui",CONFIG.poids.informations.revendiquee],["Non / mention visible",0]],
  reco:"Revendiquer et faire vérifier la fiche : sans cela, aucune optimisation n'est possible et Google limite fortement la visibilité.",
  force:"Fiche revendiquée et vérifiée — la base est en place."},
 {key:"categoriePrincipale", q:"La catégorie principale est-elle précise et pertinente ?", aide:"« Boulangerie » plutôt que « Magasin ».", max:CONFIG.poids.informations.categoriePrincipale,
  opts:[["Précise",CONFIG.poids.informations.categoriePrincipale],["Approximative",2],["Inadaptée / générique",0]],
  reco:"Choisir une catégorie principale plus précise : c'est le critère n°1 utilisé par Google pour décider sur quelles recherches afficher la fiche.",
  force:"Catégorie principale bien choisie — Google comprend l'activité."},
 {key:"categoriesSecondaires", q:"Des catégories secondaires pertinentes sont-elles définies ?", aide:"Comparer avec les concurrents les mieux positionnés.", max:CONFIG.poids.informations.categoriesSecondaires,
  opts:[["Oui",CONFIG.poids.informations.categoriesSecondaires],["Non / incomplètes",0]],
  reco:"Ajouter des catégories secondaires pour apparaître sur davantage de recherches.",
  force:"Catégories secondaires exploitées."},
 {key:"horaires", q:"Les horaires sont-ils complets, jours fériés inclus ?", aide:"Vérifier aussi les horaires spéciaux à venir.", max:CONFIG.poids.informations.horaires,
  opts:[["Complets",CONFIG.poids.informations.horaires],["Partiels",1],["Absents / faux",0]],
  reco:"Compléter les horaires, y compris les jours fériés : un « peut-être fermé » fait fuir un client prêt à se déplacer.",
  force:"Horaires complets et à jour."},
 {key:"contact", q:"Téléphone et site web sont-ils renseignés et fonctionnels ?", aide:"Tester les deux liens.", max:CONFIG.poids.informations.contact,
  opts:[["Les deux",CONFIG.poids.informations.contact],["Un seul",1],["Aucun",0]],
  reco:"Renseigner un téléphone et un site fonctionnels : ce sont les deux boutons d'action les plus utilisés par les prospects.",
  force:"Téléphone et site web opérationnels."},
 {key:"adresse", q:"L'adresse ou la zone de service est-elle exacte ?", aide:"Vérifier l'épingle sur Maps.", max:CONFIG.poids.informations.adresse,
  opts:[["Exacte",CONFIG.poids.informations.adresse],["Erreur / imprécise",0]],
  reco:"Corriger l'adresse ou la zone de service : une épingle imprécise peut réduire la confiance et compliquer le passage à l'action.",
  force:"Adresse exacte, épingle bien placée."},
 {key:"attributs", q:"Les attributs sont-ils remplis (accès, paiement, services) ?", aide:"Section « À propos » de la fiche.", max:CONFIG.poids.informations.attributs,
  opts:[["Bien remplis",CONFIG.poids.informations.attributs],["Partiels",1],["Vides",0]],
  reco:"Remplir les attributs (accessibilité, moyens de paiement, services) : ils répondent aux questions avant l'appel.",
  force:"Attributs bien renseignés."},
 {key:"nap", q:"Nom, adresse et téléphone sont-ils identiques sur le site web ?", aide:"Comparer fiche et site (pied de page, page contact).", max:CONFIG.poids.informations.nap,
  opts:[["Cohérents",CONFIG.poids.informations.nap],["Différences",0]],
  reco:"Harmoniser nom, adresse et téléphone entre la fiche et le site : les incohérences dégradent le référencement local.",
  force:"Coordonnées cohérentes entre fiche et site."}
]},
{key:"photos", cat:"Photos & visuels", pts:CONFIG.poids.photos.total, criteres:[
 {key:"logoCouverture", q:"Logo et photo de couverture sont-ils définis ?", aide:"En-tête de la fiche sur Maps.", max:CONFIG.poids.photos.logoCouverture,
  opts:[["Les deux",CONFIG.poids.photos.logoCouverture],["Un seul",1],["Aucun",0]],
  reco:"Ajouter un logo et une photo de couverture : ce sont les premiers pixels que voit un prospect.",
  force:"Logo et couverture en place — identité visuelle claire."},
 {key:"nombrePhotos", q:`La fiche compte-t-elle au moins ${CONFIG.seuils.photosNombreMax} photos ?`, aide:"Onglet Photos.", max:CONFIG.poids.photos.nombre,
  opts:[[`${CONFIG.seuils.photosNombreMax} et plus`,CONFIG.poids.photos.nombre],[`${CONFIG.seuils.photosNombreMoyen} à ${CONFIG.seuils.photosNombreMax-1}`,1],[`Moins de ${CONFIG.seuils.photosNombreMoyen}`,0]],
  reco:"Publier au moins 10 photos : les fiches bien fournies reçoivent nettement plus de demandes d'itinéraire et de clics.",
  force:"Galerie photos bien fournie."},
 {key:"photoRecente", q:`La photo la plus récente a-t-elle moins de ${CONFIG.seuils.photosRecenteMois} mois ?`, aide:"Trier les photos par date sur Maps.", max:CONFIG.poids.photos.recente,
  opts:[[`${CONFIG.seuils.photosRecenteMois} mois ou moins`,CONFIG.poids.photos.recente],[`${CONFIG.seuils.photosRecenteMois} à ${CONFIG.seuils.photosAncienneMois} mois`,2],[`Plus de ${CONFIG.seuils.photosAncienneMois} mois`,0]],
  reco:"Publier des photos récentes chaque mois : une galerie actualisée donne un signal d'activité plus rassurant.",
  force:"Photos récentes — la fiche paraît vivante."},
 {key:"varietePhotos", q:"Les photos sont-elles variées (extérieur, intérieur, équipe, réalisations) ?", aide:"Le prospect doit pouvoir se projeter.", max:CONFIG.poids.photos.variete,
  opts:[["Variées",CONFIG.poids.photos.variete],["Peu variées",1],["Un seul type",0]],
  reco:"Diversifier les photos : extérieur, intérieur, équipe, réalisations.",
  force:"Photos variées qui permettent de se projeter."},
 {key:"qualitePhotos", checklist:"qualitePhotos", q:"Les photos sont-elles de qualité professionnelle ?", aide:"Cochez la mini check-list pour limiter l'appréciation subjective.", max:CONFIG.poids.photos.qualite,
  opts:[["4-5 critères validés",CONFIG.poids.photos.qualite],["2-3 critères validés",1],["0-1 critère validé",0]],
  reco:"Remplacer les photos sombres ou floues : leur qualité perçue est transférée à la qualité perçue du service.",
  force:"Photos de bonne qualité."}
]},
{key:"avis", cat:"Avis clients", pts:CONFIG.poids.avis.total, criteres:[
 {key:"noteMoyenne", q:"Quelle est la note moyenne ?", aide:"Sous le nom de la fiche.", max:CONFIG.poids.avis.note,
  opts:[["4,5 et plus",CONFIG.poids.avis.note],["4,0 à 4,4",4],["3,5 à 3,9",2],[`Moins de ${String(CONFIG.seuils.noteMoyenne).replace(".",",")}`,0]],
  reco:"Mettre en place un parcours de collecte d'avis (QR code, demande systématique) : une note faible peut limiter la confiance au moment de comparer plusieurs fiches.",
  force:"Excellente note moyenne — un vrai capital confiance."},
 {key:"volumeAvis", q:"Le volume d'avis est-il supérieur aux concurrents directs ?", aide:"Comparer avec les 3 fiches concurrentes les mieux placées. Un écart inférieur à 10 % est considéré comparable.", max:CONFIG.poids.avis.volume,
  opts:[["Supérieur",CONFIG.poids.avis.volume],["Comparable",3],["Inférieur",0]],
  reco:"Augmenter le volume d'avis : à note égale, un volume plus élevé peut renforcer la confiance lors de la comparaison.",
  force:"Volume d'avis supérieur à la concurrence."},
 {key:"recenceAvis", q:"L'avis le plus récent a-t-il moins d'un mois ?", aide:"Trier les avis par date.", max:CONFIG.poids.avis.recence,
  opts:[["Moins d'1 mois",CONFIG.poids.avis.recence],["1 à 6 mois",2],["Plus de 6 mois",0]],
  reco:"Relancer la collecte d'avis : des avis anciens laissent penser que l'activité décline.",
  force:"Avis récents et réguliers."},
 {key:"tauxReponseAvis", q:"L'établissement répond-il aux avis ?", aide:"Vérifier les 10 derniers avis sur Maps.", max:CONFIG.poids.avis.tauxReponse,
  opts:[["Quasi tous",CONFIG.poids.avis.tauxReponse],["Une partie",3],["Rarement / jamais",0]],
  reco:"Répondre à tous les avis, positifs comme négatifs : les réponses visibles renforcent la confiance et montrent que l'entreprise suit sa relation client.",
  force:"Réponses systématiques aux avis — signal de sérieux fort."},
 {key:"qualiteReponsesAvis", checklist:"qualiteReponsesAvis", q:"Les réponses sont-elles personnalisées et professionnelles ?", aide:"Cochez la mini check-list pour évaluer la qualité des réponses de façon reproductible.", max:CONFIG.poids.avis.qualiteReponses,
  opts:[["4-5 critères validés",CONFIG.poids.avis.qualiteReponses],["2-3 critères validés",2],["0-1 critère validé",0]],
  reco:"Personnaliser les réponses aux avis et soigner celles aux avis négatifs : c'est la vitrine du service client.",
  force:"Réponses aux avis soignées et personnalisées."}
]},
{key:"contenu", cat:"Contenu de la fiche", pts:CONFIG.poids.contenu.total, criteres:[
 {key:"descriptionRemplie", q:"La description est-elle remplie (proche des 750 caractères) ?", aide:"Section « À propos » sur la fiche.", max:CONFIG.poids.contenu.descriptionRemplie,
  opts:[["Complète",CONFIG.poids.contenu.descriptionRemplie],["Courte",2],["Vide",0]],
  reco:"Rédiger une description complète (750 caractères) : c'est l'espace de vente le plus sous-exploité de la fiche.",
  force:"Description complète."},
 {key:"descriptionQualite", checklist:"qualiteDescription", q:"La description est-elle utile, locale et différenciante ?", aide:"Cochez la mini check-list : ville, services, différenciants et lisibilité.", max:CONFIG.poids.contenu.descriptionQualite,
  opts:[["4-5 critères validés",CONFIG.poids.contenu.descriptionQualite],["2-3 critères validés",2],["0-1 critère validé",0]],
  reco:"Intégrer la ville, les spécialités et les différenciants dans la description : ces éléments aident à mieux contextualiser la fiche sur les recherches pertinentes.",
  force:"Description bien ciblée (ville, spécialités, différenciants)."},
 {key:"servicesPresents", q:"Les services / produits sont-ils présents ?", aide:"Onglet Services ou Produits.", max:CONFIG.poids.contenu.servicesPresents,
  opts:[["Complets",CONFIG.poids.contenu.servicesPresents],["Partiels",1],["Absents",0]],
  reco:"Ajouter les services ou produits principaux : Google comprend mieux l'offre et le prospect trouve plus vite ce qu'il cherche.",
  force:"Services ou produits présents."},
 {key:"servicesDecrits", q:"Les services / produits sont-ils correctement décrits ?", aide:"Chaque service doit aider le prospect à comprendre l'offre sans appeler.", max:CONFIG.poids.contenu.servicesDecrits,
  opts:[["Descriptions utiles",CONFIG.poids.contenu.servicesDecrits],["Descriptions courtes",1],["Non décrits",0]],
  reco:"Détailler chaque service avec une description claire : le prospect doit comprendre l'offre sans avoir à appeler.",
  force:"Services détaillés et lisibles."},
 {key:"questionsReponses", q:"La rubrique Questions/Réponses est-elle alimentée ?", aide:"L'établissement peut poser et répondre lui-même aux questions fréquentes.", max:CONFIG.poids.contenu.questionsReponses,
  opts:[["Alimentée",CONFIG.poids.contenu.questionsReponses],["Quelques questions sans réponse",1],["Vide",0]],
  reco:"Alimenter la rubrique Q&R avec les 5 questions les plus fréquentes : cela lève les doutes avant l'appel.",
  force:"Questions/Réponses exploitée."},
 {key:"liensAction", q:"Des liens d'action sont-ils en place (RDV, devis, commande) ?", aide:"Boutons de réservation ou liens spécifiques, si pertinent.", max:CONFIG.poids.contenu.liensAction,
  opts:[["Oui",CONFIG.poids.contenu.liensAction],["Non applicable à l'activité",CONFIG.poids.contenu.liensAction],["Manquants",0]],
  reco:"Ajouter un lien de prise de rendez-vous ou de demande de devis : chaque étape évitée augmente la conversion.",
  force:"Liens d'action en place."}
]},
{key:"activite", cat:"Activité & animation", pts:CONFIG.poids.activite.total, criteres:[
 {key:"publicationRecente", q:`La dernière publication (post) date-t-elle de moins de ${CONFIG.seuils.publicationRecenteJours} jours ?`, aide:"Section « Actualités » de la fiche.", max:CONFIG.poids.activite.publicationRecente,
  opts:[[`${CONFIG.seuils.publicationRecenteJours} jours ou moins`,CONFIG.poids.activite.publicationRecente],[`Jusqu'à ${CONFIG.seuils.publicationAncienneJours} jours`,1],["Plus / jamais",0]],
  reco:"Publier au moins un post par mois (offre, nouveauté, réalisation) : une fiche animée rassure et est favorisée par Google.",
  force:"Fiche animée par des publications récentes."},
 {key:"rythmePublication", q:"Le rythme de publication est-il régulier (2+/mois) ?", aide:"Historique des posts.", max:CONFIG.poids.activite.rythmePublication,
  opts:[["Régulier",CONFIG.poids.activite.rythmePublication],["Irrégulier",1],["Inexistant",0]],
  reco:"Installer un rythme régulier de publication : la régularité compte plus que le volume.",
  force:"Rythme de publication régulier."}
]},
{key:"visibilite", cat:"Visibilité locale", pts:CONFIG.poids.visibilite.total, criteres:[
 {key:"classementLocal", q:"La fiche apparaît-elle dans le top 3 de Maps sur « métier + ville » ?", aide:"Calculé automatiquement via la recherche Google.", max:CONFIG.poids.visibilite.classement,
  opts:[["Top 3",CONFIG.poids.visibilite.classement],["Visible en 1re page",3],["Absente",0]],
  reco:"Travailler le référencement local (catégories, avis, complétude, cohérence) : hors du top 3 de Maps, la fiche capte une fraction des recherches.",
  force:"Présente dans le top 3 local — très bonne visibilité observée."},
 {key:"attractiviteConcurrents", q:"Face aux 3 concurrents directs, la fiche est-elle plus attractive ?", aide:"Comparaison note + volume d'avis calculée automatiquement avec une tolérance de 10 %.", max:CONFIG.poids.visibilite.attractivite,
  opts:[["Devant",CONFIG.poids.visibilite.attractivite],["Comparable",2],["Derrière",0]],
  reco:"Combler l'écart avec les concurrents directs : le prospect compare toujours 2-3 fiches avant de choisir.",
  force:"Fiche plus attractive que les concurrents directs."},
 {key:"recherchesSpecifiques", q:"La fiche ressort-elle sur des recherches de services spécifiques ?", aide:"Tester 2-3 recherches précises, ex. « pain sans gluten lyon ».", max:CONFIG.poids.visibilite.recherchesSpecifiques,
  opts:[["Oui",CONFIG.poids.visibilite.recherchesSpecifiques],["Partiellement",1],["Non",0]],
  reco:"Couvrir les recherches spécifiques via les services, la description et les posts : ce sont souvent les requêtes les plus proches de l'achat.",
  force:"Visible sur les recherches spécifiques."}
]}];
