export const SCORING_VERSION = "score-efficia-v4";

export const CONFIG = {
  totalScore: 100,
  seuils: {
    noteExcellente: 4.5,
    noteBonne: 4.0,
    noteMoyenne: 3.5,
    photosNombreMax: 10,
    photosNombreMoyen: 3,
    photosRecenteMois: 3,
    photosAncienneMois: 12,
    avisRecentJours: 31,
    avisAncienJours: 185,
    publicationRecenteJours: 30,
    publicationAncienneJours: 90,
    toleranceConcurrents: 0.10,
    toleranceNoteConcurrents: 0.15,
    ecartNotePenalisant: 0.30,
  },
  checklist: {
    noteMaxMinCases: 4,
    noteIntermediaireMinCases: 2,
    criteres: {
      qualitePhotos: [
        "Photos nettes",
        "Bonne luminosité",
        "Bon cadrage",
        "Résolution suffisante",
        "Absence de texte ou filigrane",
      ],
      qualiteReponsesAvis: [
        "Réponse personnalisée",
        "Ton professionnel",
        "Référence au contexte de l'avis",
        "Réponse utile ou action claire",
        "Traitement calme des critiques",
      ],
      qualiteDescription: [
        "Ville ou zone mentionnée",
        "Services principaux clairs",
        "Différenciants présents",
        "Vocabulaire naturel côté client",
        "Texte lisible sans bourrage SEO",
      ],
    },
  },
  poids: {
    informations: { total: 24, revendiquee: 3, categoriePrincipale: 4, categoriesSecondaires: 2, horaires: 3, contact: 3, adresse: 2, attributs: 2, nap: 3, nomConforme: 2 },
    photos: { total: 15, logoCouverture: 3, nombre: 3, recente: 4, variete: 3, qualite: 2 },
    avis: { total: 25, note: 6, volume: 5, recence: 4, tauxReponse: 6, qualiteReponses: 4 },
    contenu: { total: 21, descriptionRemplie: 4, descriptionQualite: 4, servicesPresents: 3, servicesDecrits: 3, questionsReponses: 3, liensAction: 4 },
    activite: { total: 5, publicationRecente: 3, rythmePublication: 2 },
    visibilite: { total: 10, classement: 6, attractivite: 4 },
  },
  secteurs: {
    default: { label: "Default", informations: 24, photos: 15, avis: 25, contenu: 21, activite: 5, visibilite: 10 },
    artisan: { label: "Artisan", informations: 24, photos: 12, avis: 27, contenu: 22, activite: 3, visibilite: 12 },
    restaurant: { label: "Restaurant", informations: 22, photos: 18, avis: 26, contenu: 20, activite: 4, visibilite: 10 },
    commerce: { label: "Commerce", informations: 21, photos: 17, avis: 25, contenu: 20, activite: 6, visibilite: 11 },
    professionLiberale: { label: "Profession libérale", informations: 25, photos: 10, avis: 27, contenu: 23, activite: 3, visibilite: 12 },
    sante: { label: "Santé", informations: 28, photos: 8, avis: 27, contenu: 22, activite: 3, visibilite: 12 },
    hebergement: { label: "Hébergement", informations: 22, photos: 20, avis: 27, contenu: 18, activite: 3, visibilite: 10 },
  },
  tempsTaches: {
    revendiquee: { bloc: "Informations", minutes: 30 },
    categoriePrincipale: { bloc: "Informations", minutes: 10 },
    categoriesSecondaires: { bloc: "Informations", minutes: 15 },
    horaires: { bloc: "Informations", minutes: 10 },
    contact: { bloc: "Informations", minutes: 10 },
    adresse: { bloc: "Informations", minutes: 15 },
    attributs: { bloc: "Informations", minutes: 15 },
    nap: { bloc: "Informations", minutes: 20 },
    logoCouverture: { bloc: "Photos", minutes: 20 },
    nombrePhotos: { bloc: "Photos", minutes: 45 },
    photoRecente: { bloc: "Photos", minutes: 20 },
    varietePhotos: { bloc: "Photos", minutes: 30 },
    qualitePhotos: { bloc: "Photos", minutes: 45 },
    noteMoyenne: { bloc: "Avis", minutes: 25 },
    volumeAvis: { bloc: "Avis", minutes: 20 },
    recenceAvis: { bloc: "Avis", minutes: 20 },
    tauxReponseAvis: { bloc: "Avis", minutes: 30 },
    qualiteReponsesAvis: { bloc: "Avis", minutes: 25 },
    descriptionRemplie: { bloc: "Contenu", minutes: 30 },
    descriptionQualite: { bloc: "Contenu", minutes: 30 },
    servicesPresents: { bloc: "Contenu", minutes: 25 },
    servicesDecrits: { bloc: "Contenu", minutes: 45 },
    questionsReponses: { bloc: "Contenu", minutes: 30 },
    liensAction: { bloc: "Contenu", minutes: 20 },
    publicationRecente: { bloc: "Animation", minutes: 20 },
    rythmePublication: { bloc: "Animation", minutes: 30 },
    classementLocal: { bloc: "Visibilité", minutes: 25 },
    attractiviteConcurrents: { bloc: "Visibilité", minutes: 20 },
    nomConforme: { bloc: "Informations", minutes: 10 },
    reponseParAvis: { bloc: "Avis", minutes: 3, plafond: 90 },
  },
};

export const BANDES = [
  { min: 85, nom: "Excellente", couleur: "#059669", verdict: "Votre fiche inspire confiance. Quelques ajustements la rendraient irréprochable." },
  { min: 70, nom: "Bonne base", couleur: "#65a30d", verdict: "Votre fiche est solide, mais des opportunités concrètes restent sur la table." },
  { min: 50, nom: "Potentiel inexploité", couleur: "#d97706", verdict: "Votre fiche dispose d'une base visible, mais plusieurs leviers peuvent encore renforcer sa capacité à rassurer et convertir." },
  { min: 0, nom: "Potentiel sous-exploité", couleur: "#dc2626", verdict: "La fiche présente plusieurs signaux incomplets. Une optimisation structurée peut améliorer sa lisibilité, sa crédibilité et son potentiel de conversion." },
];
